### ISSUE TITLE
【BUG Report】插件无法正常运行

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#5]
我在内网 window10 安装了这插件，内网的vscode 版本信息如下：

```bash
版本: 1.85.1 (user setup)
提交: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
日期: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
Chromium: 25551756
Node.js: 114.0.5735.289
V8: 18.15.0
OS: 11.4.183.29-electron.0
```
打开vscode 控制台报错信息如下（由于内网安全策略的限制，没法截图）：
```bash
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at findCurrentRoot (c:\Users\.vscode\extensions\simonhe.fast-create-variable-0.0.45\dist\index.js:89955:27)
    at findAutoImport (c:\Users\.vscode\extensions\simonhe.fast-create-variable-0.0.45\dist\index.js:89968:23)
    at runAutoImport (c:\Users\.vscode\extensions\simonhe.fast-create-variable-0.0.45\dist\index.js:89915:31)
    at f.value (c:\Users\.vscode\extensions\simonhe.fast-create-variable-0.0.45\dist\index.js:89910:5)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.z (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1972)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2188)
    at f.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:145:16612)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at i.acceptDocumentsAndEditorsDelta (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:12599)
    at i.$acceptDocumentsAndEditorsDelta (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:10970)
    at l.S (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10829)
    at l.Q (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10595)
    at l.M (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:9685)
    at l.L (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:8764)
    at f.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:7567)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at f.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:7903)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at MessagePortMain.<anonymous> (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:6183)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

安装的 fast-jump 也是报同样的错误，打开 fast-jump 的 sidebarActivity 提示 【没有可提供视图数据的已注册数据提供程序。】 文字

**Comment by Simon-He95** [comment]
应该是他里面需要获取当前激活的文本路径，但是你未点击到某一个文本

**Comment by jzsn2018** [comment]
> 应该是他里面需要获取当前激活的文本路径，但是你未点击到某一个文本

我是在一个 vue 文件中选中 template 中的属性值，然后通过 ctrl + p 选择 fast-create-variable 命令，结果vscode无任何反应，也不会出现 下拉框。
周末我在家里的 mac 上面是可以正常使用的

**Comment by Simon-He95** [comment]
> > 应该是他里面需要获取当前激活的文本路径，但是你未点击到某一个文本
> 
> 我是在一个 vue 文件中选中 template 中的属性值，然后通过 ctrl + p 选择 fast-create-variable 命令，结果vscode无任何反应，也不会出现 下拉框。 周末我在家里的 mac 上面是可以正常使用的

我设置的默认快捷键是ctrl+g

**Comment by jzsn2018** [comment]
> > > 应该是他里面需要获取当前激活的文本路径，但是你未点击到某一个文本
> > 
> > 
> > 我是在一个 vue 文件中选中 template 中的属性值，然后通过 ctrl + p 选择 fast-create-variable 命令，结果vscode无任何反应，也不会出现 下拉框。 周末我在家里的 mac 上面是可以正常使用的
> 
> 我设置的默认快捷键是ctrl+g

是的，使用 ctrl + g 快捷键也是同样无法唤起 插件。前提我已经选中的文本，并没有没选中文本

**Comment by Simon-He95** [comment]
因为我没有win的电脑，我让其他人让帮忙测试了一下，似乎是正常的，可能是由于你电脑的其他插件冲突导致的，还需要你进一步的排查

**Comment by jzsn2018** [comment]
> 因为我没有win的电脑，我让其他人让帮忙测试了一下，似乎是正常的，可能是由于你电脑的其他插件冲突导致的，还需要你进一步的排查

好的，我明天上班再试试

**Comment by jzsn2018** [comment]
我电脑内网的问题，非插件问题
